### ISSUE TITLE
A better chat app

### ISSUE THREAD

**Issue by Jadon-Jesse** [Jadon-Jesse/gameJam#4]
Maybe it would be a good idea to move away from whatsapp? I hate typing out the technical details using my 2 fucking thumbs.

**Comment by Jadon-Jesse** [comment]
Maybe we could try use slack? or google's chat app?
If you have any good alternatives, let me know

**Comment by phage-zn** [comment]
Hahahah yeah I know what you mean. Been using whatsapp on my pc to make things easier. Just took a look at slack, that looks pretty damn cool tbh, so I'm down with that. Tried to take a look at google chat and got this lovely message:
![image](https://user-images.githubusercontent.com/28393493/93714973-1e2d3c00-fb5e-11ea-8e2a-54942795e87f.png)
This is a personal account

**Comment by Jadon-Jesse** [comment]
Slack it is...

**Comment by Jadon-Jesse** [comment]
But also, not sure if you've checked out MS Teams lately? We use it at work, it's actually pretty cool (and free)

**Comment by phage-zn** [comment]
Yeah I use teams at work too, that's why I liked slack, seemed like a similar thingy. Didn't know it was free though so we can go with teams if you'd prefer that.

**Comment by Jadon-Jesse** [comment]
Just tried to install teams using my non work account. It took to long so I switched to slack. Slack seems to be working as expected. Just sent you an invite

**Comment by phage-zn** [comment]
Shweet see you on the slack boi
